# ~/.config/alacritty/alacritty.yml
# Selene Hines

window:
    padding:
        x: 4
        y: 4

font:
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic

  size: 12.0

# Colors (PaperColor - Light)
colors:
  # Default colors
  primary:
    background: '0xEEEEEE'
    foreground: '0x4D4D4C'

  # Normal colors
  normal:
    black:   '0xEDEDED'
    red:     '0xD7005F'
    green:   '0x718C00'
    yellow:  '0xD75F00'
    blue:    '0x4271AE'
    magenta: '0x8959A8'
    cyan:    '0x3E999F'
    white:   '0x4D4D4C'

  # Bright colors
  bright:
    black:   '0x969694'
    red:     '0xD7005F'
    green:   '0x718C00'
    yellow:  '0xD75F00'
    blue:    '0x4271AE'
    magenta: '0x8959A8'
    cyan:    '0x3E999F'
    white:   '0xF5F5F5'

draw_bold_text_with_bright_colors: true

window.opacity: 1.0

scrolling:

  history: 10000

window.dynamic_title: true

env:
  WINIT_X11_SCALE_FACTOR: '1.0'